# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ulysses/Documentos/jogos/IJE-MetalSlug-2017-1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ulysses/Documentos/jogos/IJE-MetalSlug-2017-1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ulysses/Documentos/jogos/IJE-MetalSlug-2017-1/CMakeFiles /home/ulysses/Documentos/jogos/IJE-MetalSlug-2017-1/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ulysses/Documentos/jogos/IJE-MetalSlug-2017-1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named game

# Build rule for target.
game: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 game
.PHONY : game

# fast build rule for target.
game/fast:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/build
.PHONY : game/fast

#=============================================================================
# Target rules for targets named engine

# Build rule for target.
engine: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 engine
.PHONY : engine

# fast build rule for target.
engine/fast:
	$(MAKE) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/build
.PHONY : engine/fast

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/menu_scene.o: src/menu_scene.cpp.o

.PHONY : src/menu_scene.o

# target to build an object file
src/menu_scene.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/menu_scene.cpp.o
.PHONY : src/menu_scene.cpp.o

src/menu_scene.i: src/menu_scene.cpp.i

.PHONY : src/menu_scene.i

# target to preprocess a source file
src/menu_scene.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/menu_scene.cpp.i
.PHONY : src/menu_scene.cpp.i

src/menu_scene.s: src/menu_scene.cpp.s

.PHONY : src/menu_scene.s

# target to generate assembly for a file
src/menu_scene.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/menu_scene.cpp.s
.PHONY : src/menu_scene.cpp.s

src/monsterAI.o: src/monsterAI.cpp.o

.PHONY : src/monsterAI.o

# target to build an object file
src/monsterAI.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/monsterAI.cpp.o
.PHONY : src/monsterAI.cpp.o

src/monsterAI.i: src/monsterAI.cpp.i

.PHONY : src/monsterAI.i

# target to preprocess a source file
src/monsterAI.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/monsterAI.cpp.i
.PHONY : src/monsterAI.cpp.i

src/monsterAI.s: src/monsterAI.cpp.s

.PHONY : src/monsterAI.s

# target to generate assembly for a file
src/monsterAI.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/monsterAI.cpp.s
.PHONY : src/monsterAI.cpp.s

src/player.o: src/player.cpp.o

.PHONY : src/player.o

# target to build an object file
src/player.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/player.cpp.o
.PHONY : src/player.cpp.o

src/player.i: src/player.cpp.i

.PHONY : src/player.i

# target to preprocess a source file
src/player.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/player.cpp.i
.PHONY : src/player.cpp.i

src/player.s: src/player.cpp.s

.PHONY : src/player.s

# target to generate assembly for a file
src/player.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/player.cpp.s
.PHONY : src/player.cpp.s

src/soldier.o: src/soldier.cpp.o

.PHONY : src/soldier.o

# target to build an object file
src/soldier.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/soldier.cpp.o
.PHONY : src/soldier.cpp.o

src/soldier.i: src/soldier.cpp.i

.PHONY : src/soldier.i

# target to preprocess a source file
src/soldier.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/soldier.cpp.i
.PHONY : src/soldier.cpp.i

src/soldier.s: src/soldier.cpp.s

.PHONY : src/soldier.s

# target to generate assembly for a file
src/soldier.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/soldier.cpp.s
.PHONY : src/soldier.cpp.s

src/stage1_scene.o: src/stage1_scene.cpp.o

.PHONY : src/stage1_scene.o

# target to build an object file
src/stage1_scene.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/stage1_scene.cpp.o
.PHONY : src/stage1_scene.cpp.o

src/stage1_scene.i: src/stage1_scene.cpp.i

.PHONY : src/stage1_scene.i

# target to preprocess a source file
src/stage1_scene.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/stage1_scene.cpp.i
.PHONY : src/stage1_scene.cpp.i

src/stage1_scene.s: src/stage1_scene.cpp.s

.PHONY : src/stage1_scene.s

# target to generate assembly for a file
src/stage1_scene.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/stage1_scene.cpp.s
.PHONY : src/stage1_scene.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... game"
	@echo "... edit_cache"
	@echo "... engine"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/menu_scene.o"
	@echo "... src/menu_scene.i"
	@echo "... src/menu_scene.s"
	@echo "... src/monsterAI.o"
	@echo "... src/monsterAI.i"
	@echo "... src/monsterAI.s"
	@echo "... src/player.o"
	@echo "... src/player.i"
	@echo "... src/player.s"
	@echo "... src/soldier.o"
	@echo "... src/soldier.i"
	@echo "... src/soldier.s"
	@echo "... src/stage1_scene.o"
	@echo "... src/stage1_scene.i"
	@echo "... src/stage1_scene.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

